---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coco-trustee.names.asConfig" . }}
  labels:
    {{- include "coco-trustee.labels" . | nindent 4 }}
data:
  config.json: |
{{ tpl (.Files.Get "files/as-config.json.template") . | nindent 4 }}
