{{- $credsDir := ((.Values.as.verifier | default dict).se | default dict).credsDir | default "" -}}
{{- if $credsDir -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coco-trustee.names.ibmse.pvc" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coco-trustee.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
{{- end }}
