{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "coco-trustee.names.kbs" . }}
  labels:
    {{- include "coco-trustee.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      {{- if .hosts }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "coco-trustee.names.kbs" . }}
                port:
                  number: {{ include "coco-trustee.port.kbs" . }}
{{- end }}
