version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    allow:
      - dependency-type: direct
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
