session_storage_type = "memory"

[http_server]
sockets = ["0.0.0.0:8080"]
insecure_http = true

[attestation_token]

[attestation_service]
type = "coco_as_grpc"
as_addr = "http://as:50004"
timeout = 5

[admin]
authorization_mode = "AuthenticatedAuthorization"

[admin.authentication.bearer_jwt]
identity_providers = [
    { issuer = "admin1-issuer", public_key_uri = "/opt/confidential-containers/trustee/admin1-pubkey.pem" },
    { issuer = "admin2-issuer", public_key_uri = "/opt/confidential-containers/trustee/admin2-pubkey.pem" },
]

[admin.authorization.regex_acl]
acls = [
    { role = "admin1", allowed_endpoints = "^/kbs/v0/resource/.+$" },
    { role = "admin2", allowed_endpoints = "^/kbs/v0/config/.+$" },
]

[storage_backend]
storage_type = "local_json"
backends.local_json.file_dir_path = "/opt/confidential-containers/trustee"
