// Copyright (c) 2024 by Alibaba.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

//! Admin module for managing admin access to the KBS server.
//!
//! This modules has two parts:
//! - token_verifier: verifies the token from the request
//! - authorization: checks if the token has access to the given path
//!
//! The workflow is as follows:
//! 1. The token verifier gets the jwt token from the request header.
//! 2. The token verifier verifies the jwt token using the pre-configured public keys and returns the claims.
//! 3. The authorization checks if the token has access to the given path.
//! 4. If the token has access to the given path, the request is allowed.
//! 5. If the token does not have access to the given path, the request is denied.

use actix_web::HttpRequest;
use serde::{Deserialize, Serialize};
use tracing::info;

pub mod authorization;
pub mod token_verifier;

pub mod error;
pub use error::*;

use crate::admin::token_verifier::TokenVerifierType;
pub use crate::admin::{
    authorization::{Authorization, AuthorizerType},
    token_verifier::TokenVerifier,
};

/// Claims are the abstraction of the claims generated by the token verifier.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq)]
pub struct Claims {
    pub issuer: String,
    pub subject: String,
    pub audiences: Vec<String>,
}

pub struct AuthorizationDecision {
    pub allowed: bool,
    pub reason: String,
}

#[derive(Clone)]
pub enum Admin {
    InsecureAllowAll,
    DenyAll,
    TokenAuthorization(TokenVerifier, Authorization),
}

#[derive(Clone, Debug, Default, Deserialize, PartialEq)]
#[serde(tag = "mode")]
pub enum AdminConfig {
    #[default]
    InsecureAllowAll,
    DenyAll,
    TokenAuthorization {
        token_verifier: TokenVerifierType,
        authorizer: AuthorizerType,
    },
}

impl Admin {
    pub async fn new(config: AdminConfig) -> Result<Self> {
        match config {
            AdminConfig::InsecureAllowAll => Ok(Admin::InsecureAllowAll),
            AdminConfig::DenyAll => Ok(Admin::DenyAll),
            AdminConfig::TokenAuthorization {
                token_verifier,
                authorizer,
            } => Ok(Admin::TokenAuthorization(
                TokenVerifier::new(token_verifier).await?,
                authorizer.try_into()?,
            )),
        }
    }

    pub fn check_admin_access(&self, request: &HttpRequest) -> Result<()> {
        match self {
            Admin::InsecureAllowAll => {
                info!("Admin access granted as AllowAll mode is enabled");
                Ok(())
            }
            Admin::DenyAll => Err(Error::AdminAccessDenied {
                reason: "Admin access denied as DenyAll mode is enabled".to_string(),
            }),
            Admin::TokenAuthorization(token_verifier, authorizer) => {
                let claims = token_verifier.parse_and_verify(request)?;
                info!(
                    "Admin access granted for {} with claims: {:?}",
                    claims.issuer, claims
                );
                let decision = authorizer.authorize(claims, request)?;
                if decision.allowed {
                    Ok(())
                } else {
                    Err(Error::AdminAccessDenied {
                        reason: decision.reason,
                    })
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;
    use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
    use openssl::pkey::PKey;
    use rstest::rstest;
    use serde_json::json;
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    #[tokio::test]
    pub async fn make_admin_object() {
        // basic (backwards compatible)
        let admin_config_json = json!({
            "mode": "InsecureAllowAll",
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let _admin = Admin::new(config).await.unwrap();

        // with invalid mode
        let admin_config_json = json!({
            "type": "AllowAll",
        });

        let config = serde_json::from_value::<AdminConfig>(admin_config_json);
        assert!(config.is_err());

        // token authorization mode / regex authorizer with invalid audience (bad regex)
        let admin_config_json = json!({
            "mode": "TokenAuthorization",
            "authorizer": {
                "type": "RegexAcl",
                "acls": [{
                    "audience": "Anonymous",
                    "allowed_endpoints": "(xyz"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "idps": [{
                    "issuer": "oidc-1",
                    "public_key_uri": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());

        // with invalid audience (duplicate audience)
        let admin_config_json = json!({
            "mode": "TokenAuthorization",
            "authorizer": {
                "type": "RegexAcl",
                "acls": [{
                    "audience": "Anonymous",
                    "allowed_endpoints": "(xyz"
                },
                {
                    "audience": "Anonymous",
                    "allowed_endpoints": "(xyz"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "idps": [{
                    "issuer": "oidc-1",
                    "public_key_uri": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());
    }

    // TODO: fix this test with Bearer token fixture
    #[ignore]
    #[tokio::test]
    pub async fn check_requests() {
        let admin_config_json = json!({
            "mode": "TokenAuthorization",
            "authorizer": {
                "type": "RegexAcl",
                "acls": [{
                    "audience": "Anonymous",
                    "allowed_endpoints": "^/resource/a/.+/c$"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "idps": [{
                    "issuer": "oidc-1",
                    "public_key_uri": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await.unwrap();

        // valid request
        let req = actix_web::test::TestRequest::post()
            .uri("/kbs/v0/resource/a/b/c")
            .to_http_request();
        admin.check_admin_access(&req).unwrap();

        // invalid request
        let req = actix_web::test::TestRequest::post()
            .uri("/kbs/v0/resource/b/b/c")
            .to_http_request();
        assert!(admin.check_admin_access(&req).is_err());
    }

    fn make_test_admin_keypair() -> (String, PathBuf) {
        let keypair = PKey::generate_ed25519().expect("generate test ed25519 keypair");
        let private_key_pem = String::from_utf8(
            keypair
                .private_key_to_pem_pkcs8()
                .expect("export test private key"),
        )
        .expect("test private key is valid utf8");
        let public_key_pem = keypair.public_key_to_pem().expect("export test public key");

        let now_nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before unix epoch")
            .as_nanos();
        let public_key_path =
            std::env::temp_dir().join(format!("kbs-admin-test-pubkey-{now_nanos}.pem"));
        fs::write(&public_key_path, public_key_pem).expect("write test admin public key");

        (private_key_pem, public_key_path)
    }

    #[rstest]
    #[case("/kbs/v0/resource/allowed/path", true)]
    #[case("/kbs/v0/resource/denied/path", false)]
    #[tokio::test]
    pub async fn check_requests_acl(#[case] request_uri: &str, #[case] expected_allowed: bool) {
        let (private_key_pem, public_key_path) = make_test_admin_keypair();

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before unix epoch")
            .as_secs();
        let claims = json!({
            "iss": "oidc-1",
            "sub": "unit-test",
            "aud": ["Alice"],
            "iat": now,
            "exp": now + 300,
        });
        let token = encode(
            &Header::new(Algorithm::EdDSA),
            &claims,
            &EncodingKey::from_ed_pem(private_key_pem.as_bytes()).expect("load test private key"),
        )
        .expect("sign test admin token");
        let admin_config_json = json!({
            "mode": "TokenAuthorization",
            "authorizer": {
                "type": "RegexAcl",
                "acls": [{
                    "audience": "Alice",
                    "allowed_endpoints": "^/kbs/v0/resource/allowed/.+$"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "idps": [{
                    "issuer": "oidc-1",
                    "public_key_uri": public_key_path
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await.unwrap();

        let req = actix_web::test::TestRequest::post()
            .uri(request_uri)
            .insert_header(("Authorization", format!("Bearer {token}")))
            .to_http_request();

        let result = admin.check_admin_access(&req);
        if expected_allowed {
            assert!(result.is_ok(), "request should be allowed by ACL");
        } else {
            let err = result.unwrap_err();
            match err {
                Error::AdminAccessDenied { reason } => assert_eq!(reason, "Audience not allowed"),
                e => panic!("expected ACL rejection, got: {e}"),
            }
        }
    }
}
