// Copyright (c) 2024 by Alibaba.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

//! Admin module for managing admin access to the KBS server.
//!
//! This modules has two parts:
//! - authentication: verifies and authenticates token from the request
//! - authorization: checks if the token has access to the given path
//!
//! The workflow is as follows:
//! 1. The authentication module gets the jwt token from the request header.
//! 2. The authentication module verifies the jwt token using the pre-configured public keys and returns the claims.
//! 3. The authorization checks if the token has access to the given path.
//! 4. If the token has access to the given path, the request is allowed.
//! 5. If the token does not have access to the given path, the request is denied.

use actix_web::HttpRequest;
use serde::{Deserialize, Serialize};
use tracing::info;

pub mod authentication;
pub mod authorization;

pub mod error;
pub use error::*;

use crate::admin::authentication::AuthenticationType;
pub use crate::admin::{
    authentication::TokenVerifier,
    authorization::{Authorization, AuthorizerType},
};

/// Claims are the abstraction of the claims generated by the token verifier.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq)]
pub struct Claims {
    pub role: String,
}

pub struct AuthorizationDecision {
    pub allowed: bool,
    pub reason: String,
}

#[derive(Clone)]
pub enum Admin {
    InsecureAllowAll,
    DenyAll,
    AuthenticatedAuthorization(TokenVerifier, Authorization),
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(tag = "authorization_mode", deny_unknown_fields)]
pub enum AdminConfig {
    InsecureAllowAll {},
    DenyAll {},
    AuthenticatedAuthorization {
        authentication: AuthenticationType,
        authorization: AuthorizerType,
    },
}

impl Default for AdminConfig {
    fn default() -> Self {
        Self::InsecureAllowAll {}
    }
}

impl AdminConfig {
    fn validate(&self) -> Result<()> {
        let AdminConfig::AuthenticatedAuthorization {
            authentication: AuthenticationType::BearerJwt(config),
            authorization: _,
        } = self
        else {
            return Ok(());
        };

        if config.identity_providers.is_empty() {
            return Err(Error::InvalidAdminConfig {
                message: "AuthenticatedAuthorization requires at least one `identity_providers` entry in [admin.authentication.bearer_jwt]".into(),
            });
        }

        for (index, idp) in config.identity_providers.iter().enumerate() {
            if idp.public_key_uri.is_none() && idp.jwk_set_uri.is_none() {
                return Err(Error::InvalidAdminConfig {
                    message: format!(
                        "identity_providers[{index}] must set `public_key_uri` and/or `jwk_set_uri`"
                    ),
                });
            }
        }

        Ok(())
    }
}

impl Admin {
    pub async fn new(config: AdminConfig) -> Result<Self> {
        config.validate()?;

        match config {
            AdminConfig::InsecureAllowAll {} => Ok(Admin::InsecureAllowAll),
            AdminConfig::DenyAll {} => Ok(Admin::DenyAll),
            AdminConfig::AuthenticatedAuthorization {
                authentication,
                authorization,
            } => Ok(Admin::AuthenticatedAuthorization(
                TokenVerifier::new(authentication).await?,
                authorization.try_into()?,
            )),
        }
    }

    pub fn check_admin_access(&self, request: &HttpRequest) -> Result<()> {
        match self {
            Admin::InsecureAllowAll => {
                info!("Admin access granted as AllowAll authorization_mode is enabled");
                Ok(())
            }
            Admin::DenyAll => Err(Error::AdminAccessDenied {
                reason: "Admin access denied as DenyAll authorization_mode is enabled".to_string(),
            }),
            Admin::AuthenticatedAuthorization(authentication, authorization) => {
                let claims = authentication.parse_and_verify(request)?;
                info!(
                    "Admin access granted for {} with claims: {:?}",
                    claims.role, claims
                );
                let decision = authorization.authorize(claims, request)?;
                if decision.allowed {
                    Ok(())
                } else {
                    Err(Error::AdminAccessDenied {
                        reason: decision.reason,
                    })
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;
    use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
    use openssl::pkey::PKey;
    use rstest::rstest;
    use serde_json::json;
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    #[tokio::test]
    pub async fn make_admin_object_from_json() {
        // basic (backwards compatible)
        let admin_config_json = json!({
            "authorization_mode": "InsecureAllowAll",
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let _admin = Admin::new(config).await.unwrap();

        // with invalid authorization_mode
        let admin_config_json = json!({
            "authorization_mode": "AllowAll",
        });

        let config = serde_json::from_value::<AdminConfig>(admin_config_json);
        assert!(config.is_err());

        // token authorization mode / regex authorization with invalid role (bad regex)
        let admin_config_json = json!({
            "authorization_mode": "AuthenticatedAuthorization",
            "authorization": {
                "regex_acl": {
                    "acls": [{
                        "role": "Anonymous",
                        "allowed_endpoints": "(xyz"
                    }]
                }
            },
            "authentication": {
                "bearer_jwt": {
                    "identity_providers": [{
                        "issuer": "oidc-1",
                        "public_key_uri": "test_data/admin/public_key.pem"
                    }]
                }
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());

        // with invalid role (duplicate role)
        let admin_config_json = json!({
            "authorization_mode": "AuthenticatedAuthorization",
            "authorization": {
                "regex_acl": {
                    "acls": [{
                        "role": "Anonymous",
                        "allowed_endpoints": "(xyz"
                    }]
                }
            },
            "authentication": {
                "bearer_jwt": {
                    "identity_providers": [{
                        "issuer": "oidc-1",
                        "public_key_uri": "test_data/admin/public_key.pem"
                    }]
                }
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());
    }

    #[tokio::test]
    async fn make_test_admin_config_toml() {
        // basic (backwards compatible)
        let admin_config_toml = r#"
            authorization_mode = "InsecureAllowAll"
        "#;

        let config: AdminConfig = toml::from_str(admin_config_toml).unwrap();
        let _admin = Admin::new(config).await.unwrap();

        // with invalid authorization_mode
        let admin_config_toml = r#"
            authorization_mode = "AllowAll"
        "#;

        let config = toml::from_str::<AdminConfig>(admin_config_toml);
        assert!(config.is_err());

        // token authorization mode / regex authorization with invalid role (bad regex)
        let admin_config_toml = r#"
            authorization_mode = "AuthenticatedAuthorization"

            [authentication.bearer_jwt]
            identity_providers = [
                { issuer = "oidc-1", public_key_uri = "test_data/admin/public_key.pem" },
            ]

            [authorization.regex_acl]
            acls = [
                { role = "Anonymous", allowed_endpoints = "(xyz" },
            ]
        "#;

        let config: AdminConfig = toml::from_str(admin_config_toml).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());

        // with invalid role (duplicate role)
        let admin_config_toml = r#"
            authorization_mode = "AuthenticatedAuthorization"

            [authentication.bearer_jwt]
            identity_providers = [
                { issuer = "oidc-1", public_key_uri = "test_data/admin/public_key.pem" },
            ]

            [authorization.regex_acl]
            acls = [
                { role = "Anonymous", allowed_endpoints = "(xyz" },
            ]
        "#;

        let config: AdminConfig = toml::from_str(admin_config_toml).unwrap();
        let admin = Admin::new(config).await;
        assert!(admin.is_err());
    }

    #[test]
    fn reject_unknown_admin_fields() {
        let with_legacy_type = r#"
            authorization_mode = "InsecureAllowAll"
            type = "Simple"
        "#;
        assert!(toml::from_str::<AdminConfig>(with_legacy_type).is_err());

        let missing_mode = r#"
            type = "Simple"
        "#;
        assert!(toml::from_str::<AdminConfig>(missing_mode).is_err());
    }

    #[test]
    fn reject_legacy_adjacent_tag_authentication_table() {
        let legacy = r#"
            authorization_mode = "AuthenticatedAuthorization"

            [authentication]
            type = "BearerJwt"
            identity_providers = [
                { issuer = "oidc-1", public_key_uri = "test_data/admin/public_key.pem" },
            ]

            [authorization.regex_acl]
            acls = [{ role = "admin", allowed_endpoints = "^/kbs/.+$" }]
        "#;
        assert!(toml::from_str::<AdminConfig>(legacy).is_err());
    }

    #[tokio::test]
    async fn reject_empty_identity_providers() {
        let config: AdminConfig = serde_json::from_value(json!({
            "authorization_mode": "AuthenticatedAuthorization",
            "authentication": {
                "bearer_jwt": {
                    "identity_providers": []
                }
            },
            "authorization": {
                "regex_acl": {
                    "acls": [{ "role": "admin", "allowed_endpoints": "^/kbs/.+$" }]
                }
            }
        }))
        .unwrap();

        let result = Admin::new(config).await;
        assert!(matches!(result, Err(Error::InvalidAdminConfig { .. })));
    }

    // TODO: fix this test with Bearer token fixture
    #[ignore]
    #[tokio::test]
    pub async fn check_requests() {
        let admin_config_json = json!({
            "authorization_mode": "AuthenticatedAuthorization",
            "authorization": {
                "regex_acl": {
                    "acls": [{
                        "role": "Anonymous",
                        "allowed_endpoints": "^/resource/a/.+/c$"
                    }]
                }
            },
            "authentication": {
                "bearer_jwt": {
                    "identity_providers": [{
                        "issuer": "oidc-1",
                        "public_key_uri": "test_data/admin/public_key.pem"
                    }]
                }
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await.unwrap();

        // valid request
        let req = actix_web::test::TestRequest::post()
            .uri("/kbs/v0/resource/a/b/c")
            .to_http_request();
        admin.check_admin_access(&req).unwrap();

        // invalid request
        let req = actix_web::test::TestRequest::post()
            .uri("/kbs/v0/resource/b/b/c")
            .to_http_request();
        assert!(admin.check_admin_access(&req).is_err());
    }

    fn make_test_admin_keypair() -> (String, PathBuf) {
        let keypair = PKey::generate_ed25519().expect("generate test ed25519 keypair");
        let private_key_pem = String::from_utf8(
            keypair
                .private_key_to_pem_pkcs8()
                .expect("export test private key"),
        )
        .expect("test private key is valid utf8");
        let public_key_pem = keypair.public_key_to_pem().expect("export test public key");

        let now_nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before unix epoch")
            .as_nanos();
        let public_key_path =
            std::env::temp_dir().join(format!("kbs-admin-test-pubkey-{now_nanos}.pem"));
        fs::write(&public_key_path, public_key_pem).expect("write test admin public key");

        (private_key_pem, public_key_path)
    }

    #[rstest]
    #[case(
        "/kbs/v0/admin/allowed/path",
        "oidc-1",
        &["example1.io", "example2.io"],
        "oidc-1",
        "example1.io",
        true
    )]
    #[case(
        "/kbs/v0/admin/allowed/path",
        "oidc-2",
        &["example1.io", "example2.io"],
        "oidc-1",
        "example1.io",
        false
    )]
    #[case(
        "/kbs/v0/admin/allowed/path",
        "oidc-1",
        &["wrong.example.io"],
        "oidc-1",
        "example.io",
        false
    )]
    #[case(
        "/kbs/v0/admin/denied/path",
        "oidc-1",
        &["example1.io", "example2.io"],
        "oidc-1",
        "example1.io",
        false
    )]
    #[tokio::test]
    pub async fn check_requests_acl(
        #[case] request_uri: &str,
        #[case] token_issuer: &str,
        #[case] token_audience: &[&str],
        #[case] expected_issuer: &str,
        #[case] expected_audience: &str,
        #[case] expected_allowed: bool,
    ) {
        let (private_key_pem, public_key_path) = make_test_admin_keypair();

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before unix epoch")
            .as_secs();
        let claims = json!({
            "iss": token_issuer,
            "role": "Alice",
            "aud": token_audience,
            "iat": now,
            "exp": now + 300,
        });
        let token = encode(
            &Header::new(Algorithm::EdDSA),
            &claims,
            &EncodingKey::from_ed_pem(private_key_pem.as_bytes()).expect("load test private key"),
        )
        .expect("sign test admin token");
        let admin_config_json = json!({
            "authorization_mode": "AuthenticatedAuthorization",
            "authorization": {
                "regex_acl": {
                    "acls": [{
                        "role": "Alice",
                        "allowed_endpoints": "^/kbs/v0/admin/allowed/.+$"
                    }]
                }
            },
            "authentication": {
                "bearer_jwt": {
                    "identity_providers": [{
                        "issuer": expected_issuer,
                        "audience": expected_audience,
                        "public_key_uri": public_key_path
                    }]
                }
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::new(config).await.unwrap();

        let req = actix_web::test::TestRequest::post()
            .uri(request_uri)
            .insert_header(("Authorization", format!("Bearer {token}")))
            .to_http_request();

        let result = admin.check_admin_access(&req);
        if expected_allowed {
            assert!(result.is_ok(), "request should be allowed by ACL");
        } else {
            let err = result.unwrap_err();
            match err {
                Error::AdminAccessDenied { reason } => assert!(
                    reason.contains("not allowed")
                        || reason.contains("Cannot verify token with any of the issuers")
                ),
                e => panic!("expected ACL rejection, got: {e}"),
            }
        }
    }
}
