[package]
name = "policy-engine"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
hex.workspace = true
key-value-storage.path = "../key-value-storage"
regorus.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio.workspace = true
