version: '3.2'
services:
  kbs:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.coco-as-grpc
    image: ghcr.io/confidential-containers/key-broker-service:latest
    command: [
        "/usr/local/bin/kbs",
        "--config-file",
        "/etc/kbs-config.toml",
      ]
    restart: always # keep the server running
    ports:
      - "8080:8080"
    volumes:
      - ./data/kbs-storage:/opt/confidential-containers/kbs/repository:rw
      - ./config/public.pub:/opt/confidential-containers/kbs/user-keys/public.pub
      - ./config/docker-compose/kbs-config.toml:/etc/kbs-config.toml
    depends_on:
    - as

  as:
    image: ghcr.io/confidential-containers/attestation-service:latest
    ports:
    - "50004:50004"
    restart: always
    volumes:
    - ./data/attestation-service:/opt/confidential-containers/attestation-service:rw
    - ./config/as-config.json:/etc/as-config.json:rw
    - ./config/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf:rw
    command: [
      "grpc-as",
      "--socket",
      "0.0.0.0:50004",
      "--rvps-address",
      "http://rvps:50003",
      "--config",
      "/etc/as-config.json"
    ]
    depends_on:
    - rvps

  rvps:
    image: ghcr.io/confidential-containers/reference-value-provider-service:latest
    restart: always # keep the server running
    ports:
      - "50003:50003"
    volumes:
      - ./data/reference-values:/opt/confidential-containers/attestation-service/reference_values:rw

  keyprovider:
    image: ghcr.io/confidential-containers/coco-keyprovider:latest
    restart: always
    ports:
      - "50000:50000"
    volumes:
      - ./config/private.key:/etc/private.key
    command: [
      "coco_keyprovider",
      "--socket",
      "0.0.0.0:50000",
      "--kbs",
      "http://kbs:8080",
      "--auth-private-key",
      "/etc/private.key"
    ]
    depends_on:
    - kbs
