apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../base

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kbs
  path: patch.yaml

secretGenerator:
# Store keys that KBS will release to workloads after attestation:
# kbs:///reponame/workload_key/key.bin
- name: keys
  files:
  - key.bin
