apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../../overlays/x86_64

patches:
- path: patch.yaml
  target:
    group: ""
    kind: Service
    name: kbs
