[package]
name = "grpc-as"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
as-types = { path = "../../as-types" }
async-trait.workspace = true
attestation-service = { path = "../../attestation-service", features = ["rvps-grpc"] }
clap.workspace = true
env_logger.workspace = true
log.workspace = true
prost.workspace = true
serde_json.workspace = true
shadow-rs.workspace = true
tokio.workspace = true
tonic.workspace = true

[build-dependencies]
shadow-rs.workspace = true
tonic-build.workspace = true
