FROM rust:1.67 as builder

WORKDIR /usr/src/kbs
COPY . .

RUN apt-get update && apt install -y protobuf-compiler

# Build and Instll KBS
RUN cargo install --path src/kbs --no-default-features --features grpc-as,rustls


FROM ubuntu:22.04

COPY --from=builder /usr/local/cargo/bin/kbs /usr/local/bin/kbs
