[package]
name = "as-types"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: update to 0.3, once released
kbs-types = { git = "https://github.com/mkulke/kbs-types.git", branch = "mkulke/add-az-snp-vtpm-tee-on-v0.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
