FROM rust:latest as builder

WORKDIR /usr/src/kbs
COPY . .

RUN apt-get update && apt install -y wget

RUN wget https://go.dev/dl/go1.20.1.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

# Build and Install KBS
RUN cargo install --path kbs/src/kbs --no-default-features --features intel-trust-authority-as,rustls,resource,opa

FROM ubuntu:22.04

LABEL org.opencontainers.image.source="https://github.com/confidential-containers/kbs"

RUN apt update && apt install -y ca-certificates

COPY --from=builder /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
COPY --from=builder /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
COPY --from=builder /usr/local/cargo/bin/kbs /usr/local/bin/kbs
