apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../nodeport

patches:
- path: set_custom_pccs.yaml
  target:
    kind: Deployment
    name: kbs

configMapGenerator:
- files:
  - sgx_default_qcnl.conf
  name: dcap-attestation-conf
