[http_server]
sockets = ["0.0.0.0:8080"]
# Ideally we should use some solution like cert-manager to issue let's encrypt based certificate:
# https://cert-manager.io/docs/configuration/acme/
insecure_http = true

[attestation_token]
trusted_jwk_sets = ["https://portal.trustauthority.intel.com"]

[attestation_service]
type = "intel_ta"
base_url = "https://api.trustauthority.intel.com"
api_key = "tBfd5kKX2x9ahbodKV1..."
certs_file = "https://portal.trustauthority.intel.com"

[admin]
mode = "TokenAuthorization"

[admin.token_verifier]
type = "BearerJwt"
idps = [{ issuer = "admin", public_key_uri = "/kbs/kbs.pem" }]

[admin.authorizer]
type = "RegexAcl"
acls = [{ audience = "admin", allowed_endpoints = "^/kbs/.+$" }]

[[plugins]]
name = "resource"
type = "kvstorage"

[storage_backend]
storage_type = "LocalFs"

[storage_backend.backends.local_fs]
dir_path = "/opt/confidential-containers/kbs"
