apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../../overlays/s390x

patches:
- path: patch.yaml
  target:
    group: ""
    kind: Service
    name: kbs
