# Copyright (c) 2025 by Red Hat.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

FROM fedora:latest

COPY target/release/restful-as /usr/local/bin/restful-as

CMD ["restful-as", "--socket", "0.0.0.0:50004"]

EXPOSE 50004
