// Copyright (c) 2026 by Trustee Contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Health service setup for KBS plugin servers.
//!
//! Integrates with `tonic-health` to provide automatic
//! `grpc.health.v1.Health` service registration. When KBS connects to a
//! plugin, it uses the standard gRPC health checking protocol to verify
//! the plugin is serving. This module ensures the health service reports
//! SERVING status for the KbsPlugin service automatically.

pub(crate) use tonic_health::server::health_reporter;
pub(crate) use tonic_health::ServingStatus;

/// The gRPC service name registered for health checking.
///
/// This matches the `SERVICE_NAME` constant generated by tonic for the
/// `KbsPlugin` service (`"kbs.plugin.v1.KbsPlugin"`).
pub(crate) const PLUGIN_SERVICE_NAME: &str = crate::plugin::kbs_plugin_server::SERVICE_NAME;
