[package]
name = "trustee-config"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
dirs = "6.0.0"
nix = { version = "0.30.1", features = ["user"] }
