name: Build and Push CoCoAS / RVPS Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_file: attestation-service/Dockerfile.as-grpc
            tag: coco-as-grpc
            name: gRPC CoCo-AS
          - docker_file: attestation-service/Dockerfile.as-restful
            tag: coco-as-restful
            name: RESTful CoCo-AS
          - docker_file: attestation-service/rvps/Dockerfile
            tag: rvps
            name: RVPS

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ${{ matrix.name }} Container Image
      run: |
        commit_sha=${{ github.sha }}
        DOCKER_BUILDKIT=1 docker build -t ghcr.io/confidential-containers/staged-images/${{ matrix.tag }}:${commit_sha} -t ghcr.io/confidential-containers/staged-images/${{ matrix.tag }}:latest . -f ${{ matrix.docker_file }} --push
