on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    
    - name: Build Container Image
      run: |
        DOCKER_BUILDKIT=1 docker build -t kbs:native-as . -f docker/Dockerfile; \
        DOCKER_BUILDKIT=1 docker build -t kbs:grpc-as . -f docker/Dockerfile.grpc-as