name: e2e

on:
  pull_request:
    branches: [ "main" ]

# Self-hosted runners do not set -o pipefail otherwise
defaults:
  run:
    shell: bash

jobs:
  e2e-test:
    strategy:
      matrix:
        tee:
        - sample
        # - az-snp-vtpm

    runs-on: ${{ ((matrix.tee == 'az-snp-vtpm') && fromJSON('["self-hosted","azure-cvm"]')) || 'ubuntu-22.04' }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Set up rust build cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/
        key: rust-${{ hashFiles('./Cargo.lock') }}

    - name: Install dependencies
      working-directory: test
      run: sudo make install-dependencies

    - name: Build bins
      working-directory: test
      run: make bins

    - name: Set cc_kbc sample attester env
      if: matrix.tee == 'sample'
      run: echo "AA_SAMPLE_ATTESTER_TEST=1" >> "$GITHUB_ENV"

    - name: Run e2e test
      working-directory: test
      run: sudo -E make e2e-test
