name: KBS e2e with sample TEE

on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Archive source
      run: git archive -o kbs.tar.gz HEAD

    - uses: actions/upload-artifact@v4
      with:
        path: ./kbs.tar.gz

  e2e-test:
    needs: checkout
    uses: confidential-containers/kbs/.github/workflows/kbs-e2e.yml@main
    with:
      sample: true
      tarball: kbs.tar.gz
