name: Build and Push KBS Image

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build_and_push_kbs_image:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-kbs-image.yml
    with:
      build_option: --push
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_multi_arch_image:
    needs: build_and_push_kbs_image
    strategy:
      fail-fast: false
      matrix:
        image:
          - kbs
          - kbs-grpc-as
    permissions:
      packages: write
    runs-on: ubuntu-24.04

    steps:
    - name: Login to GHCR Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Multi-Arch ${{ matrix.image }} image
      run: |
        commit_sha=${{ github.sha }}
        docker manifest create "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:${commit_sha}" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:${commit_sha}-x86_64" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:${commit_sha}-aarch64" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:${commit_sha}-s390x"
        docker manifest push "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:${commit_sha}"
        docker manifest create "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:latest" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:latest-x86_64" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:latest-aarch64" \
          --amend "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:latest-s390x"
        docker manifest push "ghcr.io/confidential-containers/staged-images/${{ matrix.image }}:latest"
