name: Cut Release

on:
  release:
    types: [published]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push kbs (With built-in CoCo AS)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/confidential-containers/key-broker-service:built-in-as-${{ github.ref_name }}
      -
        name: Build and push kbs (With the CoCo gRPC AS)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.coco-as-grpc
          platforms: linux/amd64
          push: true
          tags: ghcr.io/confidential-containers/key-broker-service:${{ github.ref_name }}, ghcr.io/confidential-containers/key-broker-service:latest
