on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Rust toolchain installation
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-gnu

    - name: Protocol buffer compiler installation
      run: |
        sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Build
      run: make kbs

    - name: Lint
      run: make lint

    - name: Format
      run: make format

    - name: Test
      run: make check
