on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Rust toolchain installation
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-gnu

    - name: Building dependencies installation
      run: |
        sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev libtss2-dev

    - name: Install TPM dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtss2-dev

    - name: Install TDX dependencies
      run: |
        sudo curl -L https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
        sudo echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
        sudo apt-get update
        sudo apt-get install -y libtdx-attest-dev libsgx-dcap-quote-verify-dev

    - name: KBS Build [Default]
      run: make

    - name: KBS Build [Built-in CoCo AS, OpenSSL]
      run: make HTTPS_CRYPTO=openssl

    - name: KBS Build [gRPC CoCo AS, RustTLS]
      run: make COCO_AS_INTEGRATE_TYPE=grpc

    - name: build KBS with amber AS mode
      run: make AS_TYPE=amber-as

    - name: Lint
      run: make lint

    - name: Format
      run: make format

    - name: Test
      run: make check
